export {LoginPage} from './Authentication/LoginPage/LoginPage'
export {SignUpPage} from './Authentication/SignUpPage/SignUpPage'
export{HomePage} from './HomePage/HomePage'
export {ProfilePage} from './ProfilePage/ProfilePage'
export {BookmarkPage} from './Bookmarks/BookmarksPage'
export {ExplorePage} from './Explore/ExplorePage'